# Generated by Django 5.0.3 on 2025-04-25 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_backend", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productreview",
            name="delivery",
        ),
    ]
